#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The RISC-V Trusted Firmware contributors
"""Kconfig front-end built on kconfiglib.

Commands (all take the build directory via --out):
  defconfig <file>     load a defconfig, write .config, generate outputs
  olddefconfig         resolve .config against the current Kconfig tree
  alldefconfig         every symbol at its default value
  savedefconfig <file> write a minimal defconfig from .config
  listnewconfig        list symbols that .config does not set
  menuconfig|guiconfig interactive editors (kconfiglib)
  sync                 write .config back + auto.conf/.d + autoconf.h

Environment: srctree (Kconfig root), KCONFIG_CONFIG (path of .config).
"""

import argparse
import os
import sys

import kconfiglib
from kconfiglib import BOOL, HEX, INT, STRING, TRISTATE


def die(msg):
    sys.stderr.write("kconfig: %s\n" % msg)
    sys.exit(1)


def load_kconfig():
    srctree = os.environ.get("srctree", ".")
    root = os.path.join(srctree, "Kconfig")
    return kconfiglib.Kconfig(root, warn_to_stderr=True, suppress_traceback=True)


def load_config(kconf, path, must_exist=True):
    if not os.path.exists(path):
        if must_exist:
            die("%s does not exist" % path)
        return
    msg = kconf.load_config(path)
    if msg:
        print(msg)


def write_outputs(kconf, out, config):
    """.config (synced), auto.conf, auto.conf.d, include/generated/autoconf.h"""
    os.makedirs(os.path.join(out, "include", "generated"), exist_ok=True)

    msg = kconf.write_config(config)
    if msg:
        print(msg)

    kconf.write_autoconf(os.path.join(out, "include", "generated", "autoconf.h"))

    auto_conf = os.path.join(out, "auto.conf")
    lines = ["# Generated by scripts/kconfig.py - do not edit\n"]
    for sym in kconf.unique_defined_syms:
        if not sym._write_to_conf:
            continue
        val = sym.str_value
        if sym.type in (BOOL, TRISTATE):
            if val == "n":
                continue
            lines.append("CONFIG_%s=%s\n" % (sym.name, val))
        elif sym.type in (INT, HEX):
            lines.append("CONFIG_%s=%s\n" % (sym.name, val))
        elif sym.type == STRING:
            # Raw string for Make: no surrounding quotes; make-special chars escaped
            val = val.replace("$", "$$").replace("#", "\\#")
            lines.append("CONFIG_%s=%s\n" % (sym.name, val))
    with open(auto_conf, "w") as f:
        f.writelines(lines)

    # Dependency fragment: auto.conf must be regenerated when any Kconfig file
    # that was read changes (covers glob 'source' directives).
    deps = sorted(set(os.path.abspath(p) for p in kconf.kconfig_filenames))
    with open(auto_conf + ".d", "w") as f:
        f.write("%s: %s\n" % (auto_conf, " \\\n\t".join(deps)))
        for d in deps:
            f.write("%s:\n" % d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="build directory")
    ap.add_argument("command")
    ap.add_argument("arg", nargs="?")
    args = ap.parse_args()

    config = os.environ.get("KCONFIG_CONFIG", os.path.join(args.out, ".config"))
    os.environ["KCONFIG_CONFIG"] = config
    kconf = load_kconfig()
    cmd = args.command

    if cmd == "defconfig":
        if not args.arg:
            die("defconfig needs a file")
        load_config(kconf, args.arg)
        write_outputs(kconf, args.out, config)
    elif cmd == "olddefconfig":
        load_config(kconf, config)
        write_outputs(kconf, args.out, config)
    elif cmd == "alldefconfig":
        write_outputs(kconf, args.out, config)
    elif cmd == "savedefconfig":
        if not args.arg:
            die("savedefconfig needs an output file")
        load_config(kconf, config)
        print(kconf.write_min_config(args.arg))
    elif cmd == "listnewconfig":
        load_config(kconf, config)
        for sym in kconf.unique_defined_syms:
            if sym.visibility and sym.user_value is None:
                print("CONFIG_%s=%s" % (sym.name, sym.str_value))
    elif cmd in ("menuconfig", "guiconfig"):
        load_config(kconf, config, must_exist=False)
        import importlib
        importlib.import_module(cmd).__dict__[cmd](kconf)
        load_config(kconf, config)
        write_outputs(kconf, args.out, config)
    elif cmd == "sync":
        load_config(kconf, config)
        write_outputs(kconf, args.out, config)
    else:
        die("unknown command '%s'" % cmd)


if __name__ == "__main__":
    main()
