/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2026, The RISC-V Trusted Firmware contributors
 */

#ifndef SBI_SBI_H
#define SBI_SBI_H

#include <compiler.h>
#include <util.h>

/* RISC-V SBI specification: error codes and extension IDs. */

#define SBI_SUCCESS 0
#define SBI_ERR_FAILED -1
#define SBI_ERR_NOT_SUPPORTED -2
#define SBI_ERR_INVALID_PARAM -3
#define SBI_ERR_DENIED -4
#define SBI_ERR_INVALID_ADDRESS -5
#define SBI_ERR_ALREADY_AVAILABLE -6
#define SBI_ERR_ALREADY_STARTED -7
#define SBI_ERR_ALREADY_STOPPED -8
#define SBI_ERR_NO_SHMEM -9
#define SBI_ERR_INVALID_STATE -10
#define SBI_ERR_BAD_RANGE -11
#define SBI_ERR_TIMEOUT -12
#define SBI_ERR_IO -13
#define SBI_ERR_DENIED_LOCKED -14

#define SBI_EXT_BASE 0x10
#define SBI_EXT_TIME 0x54494D45
#define SBI_EXT_IPI 0x735049
#define SBI_EXT_RFENCE 0x52464E43
#define SBI_EXT_HSM 0x48534D
#define SBI_EXT_SRST 0x53525354
#define SBI_EXT_PMU 0x504D55
#define SBI_EXT_DBCN 0x4442434E
#define SBI_EXT_SUSP 0x53555350
#define SBI_EXT_CPPC 0x43505043
#define SBI_EXT_NACL 0x4E41434C
#define SBI_EXT_STA 0x535441
#define SBI_EXT_SSE 0x535345
#define SBI_EXT_FWFT 0x46574654
#define SBI_EXT_DBTR 0x44425452
#define SBI_EXT_MPXY 0x4D505859

/* Legacy (SBI v0.1) extensions: one EID per call, only a0 is returned. */
#define SBI_EXT_LEGACY_SET_TIMER 0x00
#define SBI_EXT_LEGACY_PUTCHAR 0x01
#define SBI_EXT_LEGACY_GETCHAR 0x02
#define SBI_EXT_LEGACY_CLEAR_IPI 0x03
#define SBI_EXT_LEGACY_SEND_IPI 0x04
#define SBI_EXT_LEGACY_RFENCE_I 0x05
#define SBI_EXT_LEGACY_SFENCE_VMA 0x06
#define SBI_EXT_LEGACY_SFENCE_VMA_ASID 0x07
#define SBI_EXT_LEGACY_SHUTDOWN 0x08

/* Base extension function IDs. */
#define SBI_BASE_GET_SPEC_VERSION 0
#define SBI_BASE_GET_IMPL_ID 1
#define SBI_BASE_GET_IMPL_VERSION 2
#define SBI_BASE_PROBE_EXTENSION 3
#define SBI_BASE_GET_MVENDORID 4
#define SBI_BASE_GET_MARCHID 5
#define SBI_BASE_GET_MIMPID 6

#define SBI_TIME_SET_TIMER 0

#define SBI_IPI_SEND_IPI 0

#define SBI_RFENCE_FENCE_I 0
#define SBI_RFENCE_SFENCE_VMA 1
#define SBI_RFENCE_SFENCE_VMA_ASID 2
#define SBI_RFENCE_HFENCE_GVMA_VMID 3
#define SBI_RFENCE_HFENCE_GVMA 4
#define SBI_RFENCE_HFENCE_VVMA_ASID 5
#define SBI_RFENCE_HFENCE_VVMA 6

#define SBI_HSM_HART_START 0
#define SBI_HSM_HART_STOP 1
#define SBI_HSM_HART_GET_STATUS 2
#define SBI_HSM_HART_SUSPEND 3

#define SBI_HSM_STATE_STARTED 0
#define SBI_HSM_STATE_STOPPED 1
#define SBI_HSM_STATE_START_PENDING 2
#define SBI_HSM_STATE_STOP_PENDING 3
#define SBI_HSM_STATE_SUSPENDED 4
#define SBI_HSM_STATE_SUSPEND_PENDING 5
#define SBI_HSM_STATE_RESUME_PENDING 6

#define SBI_HSM_SUSPEND_RET_DEFAULT UL(0x00000000)
#define SBI_HSM_SUSPEND_RET_PLATFORM UL(0x10000000)
#define SBI_HSM_SUSPEND_NON_RET_DEFAULT UL(0x80000000)
#define SBI_HSM_SUSPEND_NON_RET_PLATFORM UL(0x90000000)

#define SBI_SRST_SYSTEM_RESET 0

#define SBI_SRST_TYPE_SHUTDOWN 0
#define SBI_SRST_TYPE_COLD_REBOOT 1
#define SBI_SRST_TYPE_WARM_REBOOT 2
#define SBI_SRST_REASON_NONE 0
#define SBI_SRST_REASON_SYSTEM_FAILURE 1

#define SBI_DBCN_CONSOLE_WRITE 0
#define SBI_DBCN_CONSOLE_READ 1
#define SBI_DBCN_CONSOLE_WRITE_BYTE 2

#define SBI_PMU_NUM_COUNTERS 0
#define SBI_PMU_COUNTER_GET_INFO 1
#define SBI_PMU_COUNTER_CONFIG_MATCHING 2
#define SBI_PMU_COUNTER_START 3
#define SBI_PMU_COUNTER_STOP 4
#define SBI_PMU_COUNTER_FW_READ 5
#define SBI_PMU_COUNTER_FW_READ_HI 6
#define SBI_PMU_SNAPSHOT_SET_SHMEM 7
#define SBI_PMU_EVENT_GET_INFO 8

/* event_idx = type << 16 | code */
#define SBI_PMU_EVENT_TYPE_HW 0
#define SBI_PMU_EVENT_TYPE_HW_CACHE 1
#define SBI_PMU_EVENT_TYPE_HW_RAW 2
#define SBI_PMU_EVENT_TYPE_FW 15

#define SBI_PMU_HW_CPU_CYCLES 1
#define SBI_PMU_HW_INSTRUCTIONS 2

#define SBI_PMU_FW_MISALIGNED_LOAD 0
#define SBI_PMU_FW_MISALIGNED_STORE 1
#define SBI_PMU_FW_ACCESS_LOAD 2
#define SBI_PMU_FW_ACCESS_STORE 3
#define SBI_PMU_FW_ILLEGAL_INSN 4
#define SBI_PMU_FW_SET_TIMER 5
#define SBI_PMU_FW_IPI_SENT 6
#define SBI_PMU_FW_IPI_RECEIVED 7
/* Then a sent/received pair per remote fence, in enum rfence_type order. */
#define SBI_PMU_FW_FENCE_I_SENT 8
#define SBI_PMU_FW_FENCE_I_RECEIVED 9
#define SBI_PMU_FW_HFENCE_VVMA_ASID_RECEIVED 21
#define SBI_PMU_FW_MAX 22

#define SBI_PMU_CFG_FLAG_SKIP_MATCH BIT(0)
#define SBI_PMU_CFG_FLAG_CLEAR_VALUE BIT(1)
#define SBI_PMU_CFG_FLAG_AUTO_START BIT(2)
#define SBI_PMU_CFG_FLAG_SET_VUINH BIT(3)
#define SBI_PMU_CFG_FLAG_SET_VSINH BIT(4)
#define SBI_PMU_CFG_FLAG_SET_UINH BIT(5)
#define SBI_PMU_CFG_FLAG_SET_SINH BIT(6)
#define SBI_PMU_CFG_FLAG_SET_MINH BIT(7)

#define SBI_PMU_START_FLAG_SET_INIT_VALUE BIT(0)
#define SBI_PMU_START_FLAG_INIT_SNAPSHOT BIT(1)

#define SBI_PMU_STOP_FLAG_RESET BIT(0)
#define SBI_PMU_STOP_FLAG_TAKE_SNAPSHOT BIT(1)

#define SBI_SUSP_SYSTEM_SUSPEND 0
#define SBI_SUSP_SLEEP_TYPE_SUSPEND_TO_RAM 0

#define SBI_FWFT_SET 0
#define SBI_FWFT_GET 1
#define SBI_FWFT_SET_FLAG_LOCK BIT(0)

#define SBI_FWFT_MISALIGNED_EXC_DELEG 0
#define SBI_FWFT_LANDING_PAD 1
#define SBI_FWFT_SHADOW_STACK 2
#define SBI_FWFT_DOUBLE_TRAP 3
#define SBI_FWFT_PTE_AD_HW_UPDATING 4
#define SBI_FWFT_POINTER_MASKING_PMLEN 5
#define SBI_FWFT_LOCAL_RESERVED_START 6
#define SBI_FWFT_LOCAL_PLATFORM_START UL(0x40000000)
#define SBI_FWFT_GLOBAL_RESERVED_START UL(0x80000000)
#define SBI_FWFT_GLOBAL_PLATFORM_START UL(0xc0000000)

#define SBI_SPEC_VERSION_MAJOR 3
#define SBI_SPEC_VERSION_MINOR 0

/* Vendor specific extension space: + mvendorid[23:0]. */
#define SBI_EXT_VENDOR_START 0x09000000
#define SBI_EXT_VENDOR_END 0x09ffffff

/*
 * Firmware specific extension space: domain control (<domain.h>).
 * (error, value) as everywhere; a domain goes by its index.
 */
#define SBI_EXT_FW_DOMAIN (0x0A000000 + CONFIG_SBI_IMPL_ID)
#define SBI_FW_DOMAIN_COUNT 0 /* () -> number of domains */
#define SBI_FW_DOMAIN_SELF 1 /* () -> the caller's domain */
#define SBI_FW_DOMAIN_ENTER 2 /* (domain, arg) -> what its exit passed */
#define SBI_FW_DOMAIN_EXIT 3 /* (value) -> what the next enter passed */
#define SBI_FW_DOMAIN_START 4 /* (domain) */
#define SBI_FW_DOMAIN_STOP 5 /* (domain) */
#define SBI_FW_DOMAIN_STATE 6 /* (domain) -> 1: runs, 0: stopped */

#endif
